import os

SECRET_KEY = ')%2u{@y]kOP-};43i){r<2)'
DATABASE_URL = os.environ.get('DATABASE_URL')
SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False
AFRICAS_TALKING_API_KEY = os.environ.get('AFRICAS_TALKING_API_KEY')
AUTH0_DOMAIN = os.environ.get('AUTH0_DOMAIN')
AUTH0_CLIENT_ID = os.environ.get('AUTH0_CLIENT_ID')
AUTH0_CLIENT_SECRET = os.environ.get('AUTH0_CLIENT_SECRET')
AUTHORIZE_URL = os.environ.get('AUTHORIZE_URL')
ACCESS_TOKEN_URL = os.environ.get('ACCESS_TOKEN_URL')
JWKS_URI= os.environ.get('JWKS_URI')
